#!/usr/bin/env python3

import rospy
import tf

if __name__ == '__main__':
    rospy.init_node('transform_listener')

    listener = tf.TransformListener()

    rate = rospy.Rate(10.0)
    while not rospy.is_shutdown():
        try:
            (trans, rot) = listener.lookupTransform('/chassis', '/camera', rospy.Time(0))
            rospy.loginfo("Transform from camera to chassis: translation=%s, rotation=%s", str(trans), str(rot))
        except (tf.LookupException, tf.ConnectivityException, tf.ExtrapolationException):
            pass

        rate.sleep()
