queenie:
  gripper_controller:
    type: "effort_controllers/JointGroupPositionController"
    joints:
    - gripper_extension
    - palm_riser
    - palm_left_finger
    - palm_right_finger
    - left_finger_to_tip
    - right_finger_to_tip
/queenie/gripper_controller:
  gripper_extension:
    pid: {p: 1.0, i: 0, d: 0.1}
  palm_riser:
    pid: {p: 1.0, i: 0, d: 0.1}
  palm_left_finger:
    pid: {p: 1.0, i: 0, d: 0.1}
  palm_right_finger:
    pid: {p: 1.0, i: 0, d: 0.1}
  left_finger_to_tip:
    pid: {p: 1.0, i: 0, d: 0.1}
  right_finger_to_tip:
    pid: {p: 1.0, i: 0, d: 0.1}