queenie:
  gripper_controller:
    type: "effort_controllers/JointGroupPositionController"
    joints:
    - gripper_extension
    # - palm_riser
    - palm_left_finger
    - palm_right_finger
    # - left_finger_to_tip
    # - right_finger_to_tip
  arm_controller:
    type: "effort_controllers/JointPositionController"
    joint: palm_riser
    pid: {p: 10, i: 0, d: 5}
    
/queenie/gripper_controller:
  gripper_extension:
    pid: {p: 10, i: 0, d: 5}
  # palm_riser:
  #   pid: {p: 10, i: 0, d: 5}
  palm_left_finger:
    pid: {p: 10, i: 0, d: 5}
  palm_right_finger:
    pid: {p: 10, i: 0, d: 5}
  # left_finger_to_tip:
  #   pid: {p: 1.0, i: 0, d: 0.1}
  # right_finger_to_tip:
  #   pid: {p: 1.0, i: 0, d: 0.1}
# /queenie/arm_controller:
#   palm_riser:
#   pid: {p: 10, i: 0, d: 5}