queenie:
  joint_state_controller:
    # The joint state controller handles publishing transforms for any moving joints
      type: "joint_state_controller/JointStateController"
      publish_rate: 50
      
  head_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - neck
      - palm_riser
      - palm_left_finger
      - palm_right_finger

    constraints:
      goal_time: 0.5                   # Override default
      stopped_velocity_tolerance: 0.01 # Override default
      neck:
        trajectory: 0.05               # Not enforced if unspecified
        goal: 0.02                     # Not enforced if unspecified
      palm_riser:
        goal: 0.01                     # Not enforced if unspecified
      palm_left_finger:
        trajectory: 0.05               # Not enforced if unspecified
        goal: 0.02                     # Not enforced if unspecified
      palm_right_finger:
        goal: 0.01                     # Not enforced if unspecified

    gains: # Required because we're controlling an effort interface
      neck : {p: 800, i: 0, d: 15}
      palm_riser: {p: 6000, i: 0, d: 100}
      palm_left_finger : {p: 100, i: 0, d: 5}
      palm_right_finger: {p: 100, i: 0, d: 5}

    state_publish_rate:  25            # Override default
    action_monitor_rate: 30            # Override default
    stop_trajectory_duration: 0        # Override default

  
#   gripper_controller:
#     type: "effort_controllers/JointGroupPositionController"
#     joints:
#     - neck
#     - palm_riser
#     - palm_left_finger
#     - palm_right_finger
#     # - left_finger_to_tip
#     # - right_finger_to_tip
#   # arm_controller:
#   #   type: "effort_controllers/JointPositionController"
#   #   joint: palm_riser
#   #   pid: {p: 10, i: 0, d: 5}

#   # palm_revolute_controller:
#   #   type: effort_controllers/JointPositionController
#   #   joint: palm_revolute
#   #   pid: {p: 100, i: 1.0, d: 0.0}
    
# /queenie/gripper_controller:
#   neck:
#     pid: {p: 100, i: 0, d: 15}
#   palm_riser:
#     pid: {p: 500, i: 0, d: 40}
#   palm_left_finger:
#     pid: {p: 100, i: 0, d: 5}
#   palm_right_finger:
#     pid: {p: 100, i: 0, d: 5}
#   # left_finger_to_tip:
#   #   pid: {p: 1.0, i: 0, d: 0.1}
#   # right_finger_to_tip:
#   #   pid: {p: 1.0, i: 0, d: 0.1}
# # /queenie/arm_controller:
# #   palm_riser:
# #   pid: {p: 10, i: 0, d: 5}